"""Score generated forensic explanations with an OpenAI-compatible judge model."""

from __future__ import annotations

import argparse
import json
import os
import re
import statistics
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping, Sequence

from .inference import (
    add_api_arguments,
    binary_label,
    client_from_args,
    extract_rationale,
    iter_records,
    parse_answer,
    repair_truncated_jsonl,
    write_json_atomic,
    write_records_atomic,
)


FULL_SYSTEM = """You are an independent expert evaluating the quality of an explanation generated by a face-video forgery detection model. The model predicts whether a video is real or fake and provides a rationale for its prediction.

Evaluate the rationale with respect to forensic evidence involving texture and detail, lighting, motion and temporal consistency, and physical plausibility.

Consider the following five criteria:

1. Evidence accuracy: Does the rationale identify relevant signs of manipulation or authenticity?
2. Reference alignment: Does it agree with the important visual evidence described in the reference rationale?
3. Specificity and grounding: Does it provide concrete, video-related observations rather than vague claims, unsupported assumptions, or hallucinated details?
4. Clarity and conciseness: Is the rationale coherent, direct, and free from unnecessary repetition?
5. Verdict consistency: Does the rationale logically support the model's predicted real/fake label? A rationale that contradicts the ground-truth label or its own predicted label should not receive a high score.

Assign one holistic integer score from 1 to 10:
- 1 indicates an incorrect, unsupported, or contradictory rationale.
- 10 indicates an accurate, specific, concise rationale that fully aligns with the reference evidence and convincingly supports the correct verdict.

Return exactly two lines:

ANALYSIS: <a concise paragraph evaluating the rationale>
SCORE: <an integer from 1 to 10>

Do not output anything else."""

NOANSWER_SYSTEM = """You are an independent expert evaluating the quality of a forensic explanation generated for a face video.

You are intentionally not given the video's ground-truth real/fake label or the detection model's predicted label. Judge only the quality of the candidate rationale by comparing its visual reasoning with the reference rationale.

Consider four criteria:

1. Evidence accuracy and alignment: Does the candidate identify evidence that agrees with the important visual evidence in the reference rationale?
2. Specificity and grounding: Does it contain concrete, video-related observations rather than vague claims, unsupported assumptions, or hallucinated details?
3. Coverage: Does it capture the most diagnostic texture, lighting, motion, temporal, or physical-plausibility cues described by the reference?
4. Clarity and conciseness: Is it coherent, direct, and free from unnecessary repetition?

Do not infer or score a real/fake verdict as a separate criterion. Assign one holistic integer score from 1 to 10, where 1 is unsupported or strongly inconsistent with the reference evidence and 10 is accurate, specific, concise, and well aligned with the reference evidence.

Return exactly two lines:

ANALYSIS: <a concise paragraph evaluating the rationale>
SCORE: <an integer from 1 to 10>

Do not output anything else."""

SCORE_RE = re.compile(r"^\s*SCORE\s*:\s*(10|[1-9])\s*$", re.IGNORECASE | re.MULTILINE)
ANALYSIS_RE = re.compile(
    r"^\s*ANALYSIS\s*:\s*(.+?)(?=^\s*SCORE\s*:)",
    re.IGNORECASE | re.MULTILINE | re.DOTALL,
)


def required(value: Any, description: str) -> str:
    text = str(value if value is not None else "").strip()
    if not text:
        raise ValueError(f"{description} is empty")
    return text


def parse_specs(values: Sequence[str]) -> list[tuple[str, Path]]:
    specs: list[tuple[str, Path]] = []
    names: set[str] = set()
    for value in values:
        if "=" not in value:
            raise ValueError(f"--prediction must use NAME=PATH syntax: {value}")
        name, raw_path = value.split("=", 1)
        name = name.strip()
        path = Path(raw_path).expanduser().resolve()
        if not name or name in names:
            raise ValueError(f"Invalid or duplicate prediction name: {name!r}")
        if not path.is_file():
            raise FileNotFoundError(path)
        names.add(name)
        specs.append((name, path))
    return specs


def index_rows(path: Path) -> tuple[list[str], Dict[str, Dict[str, Any]]]:
    order: list[str] = []
    rows: Dict[str, Dict[str, Any]] = {}
    for index, row in enumerate(iter_records(path)):
        video_path = required(row.get("video_path"), f"{path} row {index} video_path")
        if video_path in rows:
            raise ValueError(f"Duplicate video_path in {path}: {video_path}")
        order.append(video_path)
        rows[video_path] = row
    return order, rows


def sample_paths(path: Path | None) -> list[str] | None:
    if path is None:
        return None
    path = path.expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".json":
        with path.open("r", encoding="utf-8") as handle:
            value = json.load(handle)
        if not isinstance(value, list):
            raise ValueError("--sample JSON must be an array")
        selected = [
            required(item.get("video_path"), "sample video_path")
            if isinstance(item, Mapping)
            else required(item, "sample video_path")
            for item in value
        ]
    elif path.suffix.lower() == ".jsonl":
        selected = [
            required(row.get("video_path"), "sample video_path")
            for row in iter_records(path)
        ]
    else:
        selected = [
            line.strip()
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    if len(selected) != len(set(selected)):
        raise ValueError("--sample contains duplicate video paths")
    return selected


def build_messages(
    mode: str,
    reference: Mapping[str, Any],
    prediction: Mapping[str, Any],
) -> list[Dict[str, str]]:
    reference_rationale = required(extract_rationale(reference), "reference rationale")
    model_rationale = required(extract_rationale(prediction), "model rationale")
    if mode == "noanswer":
        user = (
            "Compare the candidate forensic rationale with the reference rationale.\n\n"
            f"Reference rationale:\n{reference_rationale}\n\n"
            f"Candidate rationale:\n{model_rationale}"
        )
        return [
            {"role": "system", "content": NOANSWER_SYSTEM},
            {"role": "user", "content": user},
        ]
    model_answer = parse_answer(str(prediction.get("answer", "")))
    if model_answer == "Error":
        model_answer = parse_answer(str(prediction.get("response", "")))
    user = (
        "Evaluate the following model-generated explanation.\n\n"
        f"Ground-truth answer:\n{binary_label(reference.get('label', prediction.get('label')))}\n\n"
        f"Reference rationale:\n{reference_rationale}\n\n"
        f"Model answer:\n{model_answer}\n\n"
        f"Model rationale:\n{model_rationale}"
    )
    return [
        {"role": "system", "content": FULL_SYSTEM},
        {"role": "user", "content": user},
    ]


def parse_score(text: str) -> tuple[int, str]:
    score = SCORE_RE.search(text or "")
    analysis = ANALYSIS_RE.search(text or "")
    if not score or not analysis or not analysis.group(1).strip():
        raise ValueError("Judge response must contain ANALYSIS and SCORE lines")
    return int(score.group(1)), analysis.group(1).strip()


def result_key(row: Mapping[str, Any]) -> tuple[str, str]:
    return (
        required(row.get("model"), "quality result model"),
        required(row.get("video_path"), "quality result video_path"),
    )


def existing_results(path: Path) -> Dict[tuple[str, str], Dict[str, Any]]:
    if not path.exists():
        return {}
    repair_truncated_jsonl(path)
    results: Dict[tuple[str, str], Dict[str, Any]] = {}
    for row in iter_records(path):
        results[result_key(row)] = row
    return results


def score_task(task, mode: str, client) -> Dict[str, Any]:
    name, video_path, reference, prediction = task
    base = {
        "model": name,
        "video_path": video_path,
        "mode": mode,
        "label": reference.get("label", prediction.get("label", "")),
    }
    try:
        result = client.chat(build_messages(mode, reference, prediction))
        score, analysis = parse_score(result.text)
        return {
            **base,
            "score": score,
            "analysis": analysis,
            "judge_response": result.text,
            "completion_tokens": result.completion_tokens,
            "elapsed_sec": result.elapsed_sec,
        }
    except Exception as exc:
        return {
            **base,
            "score": None,
            "analysis": "",
            "error": f"{type(exc).__name__}: {exc}",
        }


def summarize(
    rows: Iterable[Mapping[str, Any]], selected_count: int, mode: str
) -> Dict[str, Any]:
    by_model: Dict[str, list[float]] = {}
    errors: Dict[str, int] = {}
    for row in rows:
        name = str(row.get("model", ""))
        score = row.get("score")
        if isinstance(score, (int, float)):
            by_model.setdefault(name, []).append(float(score))
        else:
            errors[name] = errors.get(name, 0) + 1
    models: Dict[str, Any] = {}
    for name in sorted(set(by_model) | set(errors)):
        values = by_model.get(name, [])
        models[name] = {
            "count": len(values),
            "errors": errors.get(name, 0),
            "mean": statistics.fmean(values) if values else None,
            "median": statistics.median(values) if values else None,
            "stdev": statistics.pstdev(values)
            if len(values) > 1
            else 0.0
            if values
            else None,
            "min": min(values) if values else None,
            "max": max(values) if values else None,
        }
    return {"mode": mode, "selected_videos": selected_count, "models": models}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--references", required=True, type=Path)
    parser.add_argument(
        "--prediction", action="append", required=True, metavar="NAME=PATH"
    )
    parser.add_argument("--sample", type=Path, default=None)
    parser.add_argument("--mode", choices=("full", "noanswer"), default="full")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--summary", type=Path, default=None)
    parser.add_argument("--concurrency", type=int, default=8)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--overwrite", action="store_true")
    add_api_arguments(parser)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)
    if args.concurrency < 1:
        raise ValueError("--concurrency must be positive")
    if args.limit is not None and args.limit < 0:
        raise ValueError("--limit must be non-negative")
    reference_path = args.references.expanduser().resolve()
    reference_order, references = index_rows(reference_path)
    predictions = []
    for name, path in parse_specs(args.prediction):
        _order, rows = index_rows(path)
        predictions.append((name, rows))

    sampled = sample_paths(args.sample)
    selected = reference_order if sampled is None else sampled
    if args.limit is not None:
        selected = selected[: args.limit]
    for video_path in selected:
        if video_path not in references:
            raise ValueError(f"Reference is missing sampled video: {video_path}")
        for name, rows in predictions:
            if video_path not in rows:
                raise ValueError(
                    f"Prediction {name} is missing sampled video: {video_path}"
                )
            reference_label = str(references[video_path].get("label", "")).strip()
            prediction_label = str(rows[video_path].get("label", "")).strip()
            if args.mode == "full":
                binary_label(reference_label)
            if reference_label and prediction_label:
                if binary_label(reference_label) != binary_label(prediction_label):
                    raise ValueError(
                        f"Label mismatch for {video_path}: reference={reference_label}, "
                        f"prediction {name}={prediction_label}"
                    )

    output = args.output.expanduser().resolve()
    if output.suffix.lower() != ".jsonl":
        raise ValueError("Quality results must use a .jsonl output path")
    if args.overwrite:
        output.unlink(missing_ok=True)
    existing = existing_results(output)
    wanted = [(name, video_path) for name, _rows in predictions for video_path in selected]
    extras = set(existing) - set(wanted)
    if extras:
        raise ValueError(
            f"Existing output contains {len(extras)} results outside this run; use --overwrite"
        )
    for row in existing.values():
        if str(row.get("mode", "")) != args.mode:
            raise ValueError("Existing output uses a different scoring mode; use --overwrite")
    done = {key for key, row in existing.items() if isinstance(row.get("score"), int)}
    tasks = [
        (name, video_path, references[video_path], rows[video_path])
        for name, rows in predictions
        for video_path in selected
        if (name, video_path) not in done
    ]
    print(f"selected={len(selected)} pending_scores={len(tasks)}")
    client = client_from_args(args)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("a", encoding="utf-8", newline="\n") as handle:
        with ThreadPoolExecutor(max_workers=args.concurrency) as pool:
            futures = {
                pool.submit(score_task, task, args.mode, client): task for task in tasks
            }
            for index, future in enumerate(as_completed(futures), start=1):
                row = future.result()
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")
                handle.flush()
                existing[result_key(row)] = row
                if index % 10 == 0 or index == len(tasks):
                    os.fsync(handle.fileno())
                    print(f"scored {index}/{len(tasks)}", flush=True)

    rows = [existing[key] for key in wanted if key in existing]
    write_records_atomic(output, rows)
    summary = summarize(rows, len(selected), args.mode)
    summary_path = args.summary or output.with_name(f"{output.stem}_summary.json")
    write_json_atomic(summary_path.expanduser().resolve(), summary)
    print(f"wrote scores to {output}")
    for name, values in summary["models"].items():
        print(
            f"{name}: mean={values['mean']} count={values['count']} errors={values['errors']}"
        )


if __name__ == "__main__":
    main()
